name: artihcus_internal_chat
description: Internal chat and collaboration app for Artihcus employees.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  go_router: ^14.1.0
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.3.3
  collection: ^1.18.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

